// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OaSys.API.Data;

#nullable disable

namespace OaSys.API.Migrations
{
    [DbContext(typeof(OasysDBContext))]
    partial class OasysDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OaSys.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Audit_Log_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Audit_Log_ID"), 1L, 1);

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("FUNCTION_USED")
                        .HasColumnType("int");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("Audit_Log_ID");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("OaSys.API.Models.Customer_Account", b =>
                {
                    b.Property<int>("CUSTOMER_ACCOUNT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CUSTOMER_ACCOUNT_ID"), 1L, 1);

                    b.Property<int>("ACCOUNT_STATUS_ID")
                        .HasColumnType("int");

                    b.Property<float>("AMOUNT_OWING")
                        .HasColumnType("real");

                    b.Property<long>("CONTACT_NUMBER")
                        .HasColumnType("bigint");

                    b.Property<float>("CREDIT_LIMIT")
                        .HasColumnType("real");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PROVINCE_ID")
                        .HasColumnType("int");

                    b.Property<string>("REMINDER_MESSAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SURNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CUSTOMER_ACCOUNT_ID");

                    b.ToTable("Customer_Account");
                });

            modelBuilder.Entity("OaSys.API.Models.Employee", b =>
                {
                    b.Property<int>("EMPLOYEE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMPLOYEE_ID"), 1L, 1);

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CONTACT_NUMBER")
                        .HasColumnType("bigint");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EMPLOYEE_ID_NUMBER")
                        .HasColumnType("bigint");

                    b.Property<int>("EMPLOYEE_STATUS_ID")
                        .HasColumnType("int");

                    b.Property<int>("EMPLOYEE_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PROVINCE_ID")
                        .HasColumnType("int");

                    b.Property<string>("SURNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WARNING_ID")
                        .HasColumnType("int");

                    b.HasKey("EMPLOYEE_ID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("OaSys.API.Models.Employee_Type", b =>
                {
                    b.Property<int>("EMPLOYEE_TYPE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMPLOYEE_TYPE_ID"), 1L, 1);

                    b.Property<string>("POSITION_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("USER_ROLE_ID")
                        .HasColumnType("int");

                    b.HasKey("EMPLOYEE_TYPE_ID");

                    b.ToTable("Employee_Type");
                });

            modelBuilder.Entity("OaSys.API.Models.Order", b =>
                {
                    b.Property<int>("ORDER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ORDER_ID"), 1L, 1);

                    b.Property<DateTime>("DATE_PLACED")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DATE_RECEIVED")
                        .HasColumnType("datetime2");

                    b.Property<string>("ORDER_STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SUPPLIER_ID")
                        .HasColumnType("int");

                    b.HasKey("ORDER_ID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("OaSys.API.Models.Product", b =>
                {
                    b.Property<int>("PRODUCT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PRODUCT_ID"), 1L, 1);

                    b.Property<float>("COST_PRICE")
                        .HasColumnType("real");

                    b.Property<int>("PRODUCT_CATEGORY_ID")
                        .HasColumnType("int");

                    b.Property<string>("PRODUCT_DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUCT_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRODUCT_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<int>("QUANTITY_ON_HAND")
                        .HasColumnType("int");

                    b.Property<int>("REORDER_LIMIT")
                        .HasColumnType("int");

                    b.Property<float>("SELLING_PRICE")
                        .HasColumnType("real");

                    b.HasKey("PRODUCT_ID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("OaSys.API.Models.Product_Category", b =>
                {
                    b.Property<int>("PRODUCT_CATEGORY_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PRODUCT_CATEGORY_ID"), 1L, 1);

                    b.Property<string>("CATEGORY_DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEGORY_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRODUCT_CATEGORY_ID");

                    b.ToTable("Product_Category");
                });

            modelBuilder.Entity("OaSys.API.Models.Product_Type", b =>
                {
                    b.Property<int>("PRODUCT_TYPE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PRODUCT_TYPE_ID"), 1L, 1);

                    b.Property<int>("PRODUCT_CATEGORY_ID")
                        .HasColumnType("int");

                    b.Property<string>("TYPE_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRODUCT_TYPE_ID");

                    b.ToTable("Product_Type");
                });

            modelBuilder.Entity("OaSys.API.Models.Rate", b =>
                {
                    b.Property<int>("RATE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RATE_ID"), 1L, 1);

                    b.Property<float>("RATE_AMOUNT")
                        .HasColumnType("real");

                    b.Property<string>("RATE_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RATE_ID");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("OaSys.API.Models.Return", b =>
                {
                    b.Property<int>("RETURN_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RETURN_ID"), 1L, 1);

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("REASON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RETURN_ID");

                    b.ToTable("Return");
                });

            modelBuilder.Entity("OaSys.API.Models.Sales", b =>
                {
                    b.Property<int>("SALE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SALE_ID"), 1L, 1);

                    b.Property<int>("CUSTOMER_ACCOUNT_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TOTAL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("SALE_ID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("OaSys.API.Models.StockTake", b =>
                {
                    b.Property<int>("STOCKTAKE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STOCKTAKE_ID"), 1L, 1);

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("EMPLOYEE_ID")
                        .HasColumnType("int");

                    b.HasKey("STOCKTAKE_ID");

                    b.ToTable("Stocktake");
                });

            modelBuilder.Entity("OaSys.API.Models.Supplier", b =>
                {
                    b.Property<int>("SUPPLIER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SUPPLIER_ID"), 1L, 1);

                    b.Property<long>("ALT_NUMBER")
                        .HasColumnType("bigint");

                    b.Property<long>("CONTACT_NUMBER")
                        .HasColumnType("bigint");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("VAT_NUMBER")
                        .HasColumnType("bigint");

                    b.HasKey("SUPPLIER_ID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("OaSys.API.Models.User", b =>
                {
                    b.Property<int>("USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USER_ID"), 1L, 1);

                    b.Property<int>("EMPLOYEE_ID")
                        .HasColumnType("int");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("USER_ROLE_ID")
                        .HasColumnType("int");

                    b.Property<int>("USER_STATUS_ID")
                        .HasColumnType("int");

                    b.HasKey("USER_ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OaSys.API.Models.Warning", b =>
                {
                    b.Property<int>("WARNING_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WARNING_ID"), 1L, 1);

                    b.Property<string>("EMPLOYEE_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REASON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WARINING_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WARNING_TYPE_ID")
                        .HasColumnType("int");

                    b.HasKey("WARNING_ID");

                    b.ToTable("Warning");
                });

            modelBuilder.Entity("OaSys.API.Models.Warning_Type", b =>
                {
                    b.Property<int>("WARNING_TYPE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WARNING_TYPE_ID"), 1L, 1);

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WARNING_TYPE_ID");

                    b.ToTable("Warning_Type");
                });
#pragma warning restore 612, 618
        }
    }
}
